/*
 *Removes tag, but leaves the content between them.
 *Tag reference: https://www.w3schools.com/TAgs/
 *Yes, I know w3schools is terrible.
 */
module.exports = function(MailShine) {
	MailShine.prototype.htmlCleaners = [
		/<\/?!DOCTYPE.*?>/g,
		/<\/?a.*?>/g,
		/<\/?abbr.*?>/g,
		/<\/?acronym.*?>/g,
		/<\/?address.*?>/g,
		/<\/?applet.*?>/g,
		/<\/?area.*?>/g,
		/<\/?article.*?>/g,
		/<\/?aside.*?>/g,
		/<\/?audio.*?>/g,
		/<\/?b.*?>/g,
		/<\/?base.*?>/g,
		/<\/?basefont.*?>/g,
		/<\/?bdi.*?>/g,
		/<\/?bdo.*?>/g,
		/<\/?big.*?>/g,
		/<\/?body.*?>/g,
		/<\/?br.*?>/g,
		/<\/?button.*?>/g,
		/<\/?canvas.*?>/g,
		/<\/?caption.*?>/g,
		/<\/?center.*?>/g,
		/<\/?cite.*?>/g,
		/<\/?col.*?>/g,
		/<\/?colgroup.*?>/g,
		/<\/?datalist.*?>/g,
		/<\/?dd.*?>/g,
		/<\/?details.*?>/g,
		/<\/?dfn.*?>/g,
		/<\/?dialog.*?>/g,
		/<\/?dir.*?>/g,
		/<\/?div.*?>/g,
		/<\/?dl.*?>/g,
		/<\/?dt.*?>/g,
		/<\/?embed.*?>/g,
		/<\/?fieldset.*?>/g,
		/<\/?figcaption.*?>/g,
		/<\/?figure.*?>/g,
		/<\/?font.*?>/g,
		/<\/?footer.*?>/g,
		/<\/?form.*?>/g,
		/<\/?frame.*?>/g,
		/<\/?frameset.*?>/g,
		/<\/?head.*?>/g,
		/<\/?header.*?>/g,
		/<\/?html.*?>/g,
		/<\/?iframe.*?>/g,
		/<\/?input.*?>/g,
		/<\/?ins.*?>/g,
		/<\/?kbd.*?>/g,
		/<\/?keygen.*?>/g,
		/<\/?label.*?>/g,
		/<\/?legend.*?>/g,
		/<\/?link.*?>/g,
		/<\/?main.*?>/g,
		/<\/?map.*?>/g,
		/<\/?mark.*?>/g,
		/<\/?menu.*?>/g,
		/<\/?menuitem.*?>/g,
		/<\/?meta.*?>/g,
		/<\/?meter.*?>/g,
		/<\/?nav.*?>/g,
		/<\/?noframes.*?>/g,
		/<\/?noscript.*?>/g,
		/<\/?object.*?>/g,
		/<\/?optgroup.*?>/g,
		/<\/?option.*?>/g,
		/<\/?output.*?>/g,
		/<\/?param.*?>/g,
		/<\/?picture.*?>/g,
		/<\/?progress.*?>/g,
		/<\/?q.*?>/g,
		/<\/?rp.*?>/g,
		/<\/?rt.*?>/g,
		/<\/?ruby.*?>/g,
		/<\/?s.*?>/g,
		/<\/?samp.*?>/g,
		/<\/?section.*?>/g,
		/<\/?select.*?>/g,
		/<\/?small.*?>/g,
		/<\/?source.*?>/g,
		/<\/?span.*?>/g,
		/<\/?sub.*?>/g,
		/<\/?summary.*?>/g,
		/<\/?sup.*?>/g,
		/<\/?textarea.*?>/g,
		/<\/?time.*?>/g,
		/<\/?title.*?>/g,
		/<\/?track.*?>/g,
		/<\/?tt.*?>/g,
		/<\/?var.*?>/g,
		/<\/?video.*?>/g,
		/<\/?wbr.*?>/g,
		/<script.*?>[\s\S]*?<\/script>/g, //Removes the entire script block
		/<style.*?>[\s\S]*?<\/style>/g, //Removes the entire style block
		/<head.*?>[\s\S]*?<\/head>/g, //Removes the entire head block
		/<!--[\s\S]*?-->/g, //Removes all comment blocks
		/\s?class.*?=.*?".*?"/g, //Removes all class attributes
		/\s?data-.*?=.*?".*?"/g //Removes all data-attributes
	];

	/*
	 *Regex patterns to detect the quoted part of an email reply.
	 */
	MailShine.prototype.replyDetectors = [
		/--*?[\s]?[oO]riginal [mM]essage[\s]?-/g,
		/--*?[\s]?[fF]orwarded [mM]essage[\s]?-/g,
		/[tT]o:.*?[\s][fF]rom:.*?/g,
		/[fF]rom:.*?[\s][tT]o:.*?/g,
		/[oO]n .*?,.*?[wW]rote:/g,
		/>.*?[\s]>/g,
	];
};
